### ISSUE TITLE
AssertionError al instalar en tryton 4.6.8

### ISSUE THREAD

**Issue by emondi** [tryton-ar/subdiario#6]
Al instalar el módulo subdiario no puede iniciar el servidor tryton por el siguiente error:

```
Traceback (most recent call last):
  File "/usr/bin/trytond", line 29, in <module>
    Pool.start()
  File "/usr/lib/python3/dist-packages/trytond/pool.py", line 95, in start
    register_classes()
  File "/usr/lib/python3/dist-packages/trytond/modules/__init__.py", line 376, in register_classes
    the_module.register()
  File "/usr/lib/python3/dist-packages/trytond/modules/subdiario/__init__.py", line 14, in register
    module='subdiario', type_='model')
  File "/usr/lib/python3/dist-packages/trytond/pool.py", line 84, in register
    assert issubclass(cls.__class__, PoolMeta), cls
AssertionError: <class 'trytond.modules.subdiario.invoice.Invoice'>
```

Mirando la diferencia con el [invoice.py de account_invoice_ar](https://github.com/tryton-ar/account_invoice_ar/blob/master/invoice.py#L220) probé mover el [indicador metaclass](https://github.com/tryton-ar/subdiario/blob/master/invoice.py#L21) a la class invoice y ahí si me funciona.

De esa forma también el 2to3 me lo acepta y lo pasa a:
```
 class Invoice(metaclass=PoolMeta):
```

**Comment by emondi** [comment]
Muchas gracias!
